[project]
name = "inversion-optimisation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets==3.6.0",
    "fancy-einsum>=0.0.3",
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.7",
    "transformer-lens==2.11.0",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
